### ISSUE TITLE
simple_make.sh does not work

### ISSUE THREAD

**Issue by pizdjuk** [Zoxcore/qTox_enhanced#13]
bootstrap.sh is absent in a git tree

**Comment by zoff99** [comment]
qTox is EoL (end of life), it uses old qt5 and many other outdated stuff. it's not recommended to use it anymore.
switch to the newer (and still supported) https://github.com/Zoxcore/trifa_material
which features a .deb package: https://github.com/Zoxcore/trifa_material/releases

if you really want to build qtox refer to this isse: #24
