### ISSUE TITLE
Please release a .deb package 

### ISSUE THREAD

**Issue by the-architect-2030** [Zoxcore/qTox_enhanced#24]
Please release a .deb package for Linux

**Comment by zoff99** [comment]
qTox is EoL (end of life), it uses old qt5 and many other outdated stuff. it's not recommended to use it anymore.
switch to the newer (and still supported) https://github.com/Zoxcore/trifa_material
which features a .deb package: https://github.com/Zoxcore/trifa_material/releases

**Comment by the-architect-2030** [comment]
> qTox is EoL (end of life), it uses old qt5 and many other outdated stuff. it's not recommended to use it anymore. switch to the newer (and still supported) https://github.com/Zoxcore/trifa_material which features a .deb package: https://github.com/Zoxcore/trifa_material/releases

I have trifa, but it does not have dark mode, it's not very pleasant for the eyes. 

qTox_enhanced has flatpak image which is not working properly on my machine. And the appimages are not displaying anything on the screen, the tray icon is visible tho.

This is why i am still using qTox.

**Comment by zoff99** [comment]
you can easily build it yourself with the scripts in .localrun with docker
to build for debian 12:

```bash
git clone https://github.com/Zoxcore/qTox_enhanced
cd qTox_enhanced/.localrun/
./docker_it_deb12.sh build
./docker_it_deb12.sh
# find the files there
ls -al debian_12/artefacts/
```

run it:

```bash
cd debian_12/artefacts/
export LD_LIBRARY_PATH=$(pwd)
./qtox
```

**Comment by zoff99** [comment]
just to reiterate: do not use any version of qTox or qTox_enhanced anymore. use at your own risk.
